version: "3.5"

services:
  versatile:
    image: 'versatile-development:latest'
    build:
      context: .
    container_name: versatile
    depends_on:
      - postgresql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/versatile
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_HIKARI_SCHEMA=main
  postgresql:
    image: postgres:11.7
    container_name: postgresql
    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data
    ports:
      - 3001:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=versatile
      - POSTGRES_SCHEMA=main
    expose:
      - 3001

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 3002:6379